### ISSUE TITLE
Error on bundle exec kitchen test

### ISSUE THREAD

**Issue by ducke** [test-kitchen/kitchen-hyperv#1]
Hi Steve,
i know this is early stage of the deployment, but i love the idee of a hyper-v driver for test kitchen.
i run into an error after execute

``` posh
bundle exec kitchen test
```

``` posh
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ClientError
>>>>>> Message: Could not load the 'hyperv' driver from the load path. Please ensure that your driver is installed as a gem or included in your Gemfile if using Bundler.
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

i´m a absolute ruby newbie.
The full capture from the console
https://gist.github.com/ducke/f4041168031f80048f8c

**Comment by ducke** [comment]
Here is my repo
https://github.com/ducke/kitchen-hyperv-test

**Comment by ducke** [comment]
Add 

```
gem 'pry'
```

to my Gemfile solved this Problem

**Comment by chaim1221** [comment]
should this be closed? I'm still having the same problem. If `pry` is a dependency of `kitchen-hyperv` then it should be installed as such. If there's a reason to not include the dependency then the instructions in the `readme.md` file should be updated.
