### ISSUE TITLE
Support remote servers

### ISSUE THREAD

**Issue by usepowershell** [test-kitchen/kitchen-hyperv#10]
8:59 PM @coderanger Goal would be something like I have for Linux with Docker, I run a beefy server in Rackspace with remote docker, Travis uses kitchen-docker to launch "VMs" on it.

**Comment by lcanfield** [comment]
+1 I'd love to be able to make a hyperv server or cluster and start converging on it

**Comment by MattHodge** [comment]
:+1:

**Comment by MichaelStankiewicz** [comment]
+1 for this.  Being able to provision test kitchen vms on a remote server which is better equipped to handle the load of the additional guest vms would be ideal, rather than having to install hyper-v and instantiate vms locally on my workstation.

**Comment by superyarick** [comment]
+1 for this.  Running remotely is a must for all of our use-cases. 
Running on *nix is also a must, not just a *nice to have*. 
Test-Kitchen cross-platform magic is gone when we attempt to store disk diffs in paths "D:\MyVMs"

**Comment by thheinen** [comment]
Implemented Remote Support in 0.7.0 (#97)
