### ISSUE TITLE
Support turning off secureboot like the hyperv dsc resource

### ISSUE THREAD

**Issue by lgeinert** [test-kitchen/kitchen-hyperv#26]
We would like to be able to turn secureboot off so we can boot linux vms.

Detail here on cmdlet to do so.

https://github.com/PowerShell/xHyper-V/blob/dev/DSCResources/MSFT_xVMHyperV/MSFT_xVMHyperV.psm1#L399

**Comment by usepowershell** [comment]
Closed by #44
