### ISSUE TITLE
Can I attach multiple data disks?

### ISSUE THREAD

**Issue by aarsan** [test-kitchen/kitchen-hyperv#36]
I am working on a recipe which fires up 2 Linux VMS with 16 disks, stripes them, formats, sets up Samba, and synchs with Unison. Is there any way to use this driver to attach multiple data disks?

**Comment by usepowershell** [comment]
@aarsan not currently, though I'd take a PR that enables that.

**Comment by aarsan** [comment]
@smurawski Thanks. I got around this problem by kicking off kitchen via PowerShell which first creates the data disks, then kitchen create, then stop-vm, attach the disks, start-vm, then kitchen converge. it's a workaround but gives me much more flexibility.

**Comment by usepowershell** [comment]
I'm glad you have a workaround! I can look at adding direct support for that at some point, but it probably won't be for a while (unless someone else drops me a PR ;) )

**Comment by robbAtEBSCO** [comment]
Just noticed the 2008R2 VHD I was using didn't have SP1.  Where do you get your base VHDs from?

**Comment by usepowershell** [comment]
closed by #43
