### ISSUE TITLE
Add capablity to driver to run Linux nodes

### ISSUE THREAD

**Issue by TheLunaticScripter** [test-kitchen/kitchen-hyperv#37]
I am primarily a Windows shop that has Windows workstations running win 10 with Hyper-V on a disconnected network. I have one or two RHEL boxes that I would like to test using test-kitchen. I built a base box and attempted to run kitchen create and it failed waiting for PowerShell to respond.

**Comment by usepowershell** [comment]
@TheLunaticScripter do you have a log file from the failed create?  As long as the OS type and transport are specified (or the os can be detected) for instances, Linux guests should work just fine.

**Comment by TheLunaticScripter** [comment]
@smurawski I was on a closed network I will see if I still have the log file. I will also look and see if I configured transport correctly.
