### ISSUE TITLE
Setting resize_vhd doesn't actually resize the disk

### ISSUE THREAD

**Issue by stonesbg** [test-kitchen/kitchen-hyperv#57]
I have set the following within my kitchen.yml

`
driver:
  resize_vhd: 128GB`

The disk doesn't appear to be resizing and from looking at the resize [code](https://github.com/test-kitchen/kitchen-hyperv/blob/master/lib/kitchen/driver/powershell.rb#L182) the property that is being passed in is just -Size.  From looking at [this article](https://technet.microsoft.com/en-us/itpro/powershell/windows/hyper-v/resize-vhd) the parameter is -SizeBytes.

Not sure if that is the actual issue or not.

**Comment by kdoores** [comment]
I agree here stonesbg.  Tested on my machine and nothing was happening.  Changed to -SizeBytes and verified that it grew the HDD.  It still needs to be initialized in windows, but the vhd was actually resized.  I opened a pull request to make the change.

**Comment by usepowershell** [comment]
Fixed in 0.5.1
