### ISSUE TITLE
When running kitchen destroy a VM should be turned off

### ISSUE THREAD

**Issue by xorima** [test-kitchen/kitchen-hyperv#87]
Currently VMs are gracefully shut down, which can sometimes mean you wait for windows updates to finish

As you are deleting the VM anyway it should just turn it off and not be graceful.

**Comment by kdoores** [comment]
What's your setup look like? Things like hyperv configuration version of the machine? Generation? What version of powershell is on your host machine?

I'm unable to recreate on PS 5.1, VM version 8.3 or 9, generation 2.

However, in theory it's possible that on older version there could be a but with the interaction between the -Force and -TurnOff parameters which are both being called, where -TurnOff isn't being granted precedence. 

-Force initiates a graceful shutdown and after 5 minutes, will kill the machine if it's not off already.
-TurnOff is effectively pulling the plug. 

It may not be a terrible idea to remove the -Force anyways, just in case. If you get me that info, I can spin up a machine matching your environment and give it a shot.

```
def delete_vm_ps
        <<-REMOVE
          $null = Get-VM -ID "#{@state[:id]}" |
            Stop-VM -Force -TurnOff -PassThru |
            Remove-VM -Force
        REMOVE
end
```
